version: 1
defaults:
  model_settings:
    t2i_model: uniart/gpt-image-2
    i2i_model: uniart/gpt-image-2
    i2v_model: uniart/seedance-2.5-vip
    r2v_model: uniart/seedance-2.5-vip
    image_model: uniart/gpt-image-2
