import { useMemo, useState, type FormEvent } from "react";

import { rigProfile } from "../data/humanoid";
import { useWorkbenchStore } from "../state/workbench-store";
import type { FocusTargetState, InteractionAnchorState } from "../types";

export function InteractionAnchorPanel() {
  const timeline = useWorkbenchStore((state) => state.dialogueTimeline); const characters = useWorkbenchStore((state) => state.characters); const sceneObjects = useWorkbenchStore((state) => state.sceneObjects); const selectedCharacterId = useWorkbenchStore((state) => state.selectedCharacterId); const selectedJointId = useWorkbenchStore((state) => state.selectedJointId); const upsert = useWorkbenchStore((state) => state.upsertInteractionAnchor); const remove = useWorkbenchStore((state) => state.removeInteractionAnchor);
  const productJoints = useMemo(() => rigProfile.joints.filter((joint) => joint.control_class === "product_joint" && joint.edit_policy === "direct"), []);
  const targetOptions = useMemo(() => [...Object.values(characters).map((character) => ({ key: `character:${character.characterId}`, label: `人物 · ${character.label}` })), ...Object.values(sceneObjects).map((object) => ({ key: `scene_object:${object.sceneObjectId}`, label: `物体 · ${object.label}` })), { key: "world_point:", label: "世界点 · 输入坐标" }], [characters, sceneObjects]);
  const [editingId, setEditingId] = useState<string | null>(null); const [jointId, setJointId] = useState(productJoints.some((joint) => joint.joint_id === selectedJointId) ? selectedJointId : "hand_r"); const [targetKey, setTargetKey] = useState("world_point:"); const [world, setWorld] = useState<[string, string, string]>(["0", "1", "1"]); const [offset, setOffset] = useState<[string, string, string]>(["0", "0", "0"]); const [mode, setMode] = useState<InteractionAnchorState["contactMode"]>("grip"); const [releasePolicy, setReleasePolicy] = useState<InteractionAnchorState["releasePolicy"]>("release_at_end"); const [startSeconds, setStartSeconds] = useState("0"); const [endSeconds, setEndSeconds] = useState("1");
  const editingAnchor = editingId ? timeline.interactionAnchors.find((anchor) => anchor.interactionAnchorId === editingId) ?? null : null; const formCharacterId = editingAnchor?.characterId ?? selectedCharacterId;
  const reset = () => { setEditingId(null); setJointId(productJoints.some((joint) => joint.joint_id === selectedJointId) ? selectedJointId : "hand_r"); setTargetKey("world_point:"); setWorld(["0", "1", "1"]); setOffset(["0", "0", "0"]); setMode("grip"); setReleasePolicy("release_at_end"); setStartSeconds("0"); setEndSeconds("1"); };
  const target = (): FocusTargetState => { const [targetType, targetId] = targetKey.split(":") as [FocusTargetState["targetType"], string]; if (targetType !== "world_point") return { targetType, targetId, worldPositionM: null }; return { targetType: "world_point", targetId: editingAnchor?.contactTarget.targetType === "world_point" ? editingAnchor.contactTarget.targetId : `world-point-contact-${String(timeline.interactionAnchors.length + 1).padStart(4, "0")}`, worldPositionM: world.map(Number) as [number, number, number] }; };
  const submit = (event: FormEvent) => { event.preventDefault(); const before = timeline.interactionAnchors.length; upsert({ interactionAnchorId: editingId ?? undefined, characterId: formCharacterId, jointId, contactTarget: target(), contactMode: mode, startSeconds: Number(startSeconds), endSeconds: Number(endSeconds), offsetM: offset.map(Number) as [number, number, number], releasePolicy }); const after = useWorkbenchStore.getState().dialogueTimeline.interactionAnchors.length; if (editingId || after > before) reset(); };
  const edit = (anchor: InteractionAnchorState) => { setEditingId(anchor.interactionAnchorId); setJointId(anchor.jointId); setTargetKey(anchor.contactTarget.targetType === "world_point" ? "world_point:" : `${anchor.contactTarget.targetType}:${anchor.contactTarget.targetId}`); if (anchor.contactTarget.worldPositionM) setWorld(anchor.contactTarget.worldPositionM.map(String) as [string, string, string]); setOffset(anchor.offsetM.map(String) as [string, string, string]); setMode(anchor.contactMode); setReleasePolicy(anchor.releasePolicy); setStartSeconds(String(anchor.startSeconds)); setEndSeconds(String(anchor.endSeconds)); };
  const vectorFields = (legend: string, values: [string, string, string], setter: (value: [string, string, string]) => void) => <fieldset className="focus-world-fields"><legend>{legend}</legend>{(["X", "Y", "Z"] as const).map((axis, index) => <label key={axis}><span>{axis}</span><input type="number" step="0.01" value={values[index]} onChange={(event) => { const next = [...values] as [string, string, string]; next[index] = event.target.value; setter(next); }}/></label>)}</fieldset>;
  return <section className="interaction-panel" aria-labelledby="interaction-title"><div className="dialogue-heading"><div><p className="kicker">Contact anchors</p><h3 id="interaction-title">关节与道具接触</h3></div><span className="count-badge">{timeline.interactionAnchors.length}</span></div><p>接触锚点是时间化参考约束，不保证 IK、碰撞、抓握或物理模拟成功。</p><form className="focus-form" onSubmit={submit}><label><span>人物</span><select value={formCharacterId} disabled><option value={formCharacterId}>{characters[formCharacterId].label}</option></select></label><label><span>产品关节</span><select value={jointId} onChange={(event) => setJointId(event.target.value)}>{productJoints.map((joint) => <option key={joint.joint_id} value={joint.joint_id}>{joint.joint_id} · {joint.semantic_role}</option>)}</select></label><label><span>接触目标</span><select value={targetKey} onChange={(event) => setTargetKey(event.target.value)}>{targetOptions.map((option) => <option key={option.key} value={option.key}>{option.label}</option>)}</select></label><label><span>接触模式</span><select value={mode} onChange={(event) => setMode(event.target.value as InteractionAnchorState["contactMode"])}><option value="touch">触碰</option><option value="grip">抓握参考</option><option value="plant">固定接触</option><option value="support">支撑</option><option value="follow">跟随</option></select></label>{targetKey === "world_point:" && vectorFields("目标世界点 (m)", world, setWorld)}{vectorFields("关节相对偏移 (m)", offset, setOffset)}<label><span>开始 (s)</span><input type="number" min={0} max={timeline.durationSeconds} step="0.05" value={startSeconds} onChange={(event) => setStartSeconds(event.target.value)}/></label><label><span>结束 (s)</span><input type="number" min={0} max={timeline.durationSeconds} step="0.05" value={endSeconds} onChange={(event) => setEndSeconds(event.target.value)}/></label><label><span>结束行为</span><select value={releasePolicy} onChange={(event) => setReleasePolicy(event.target.value as InteractionAnchorState["releasePolicy"])}><option value="release_at_end">区间结束时释放</option><option value="hold_after_end">区间结束后保持</option></select></label><div className="dialogue-form-actions"><button type="submit">{editingId ? "保存接触" : "添加接触"}</button>{editingId && <button type="button" className="secondary" onClick={reset}>取消编辑</button>}</div></form>{timeline.interactionAnchors.length > 0 && <ol className="focus-track-list">{timeline.interactionAnchors.map((anchor) => <li key={anchor.interactionAnchorId}><button type="button" className="dialogue-beat-main" onClick={() => edit(anchor)}><strong>{anchor.jointId} · {anchor.contactMode} · {anchor.startSeconds.toFixed(2)}–{anchor.endSeconds.toFixed(2)}s</strong><span>{anchor.characterId} → {anchor.contactTarget.targetId}</span><small>{anchor.releasePolicy === "release_at_end" ? "结束时释放" : "结束后保持"} · 非物理解算</small></button><button type="button" className="dialogue-remove" aria-label={`删除接触锚点 ${anchor.interactionAnchorId}`} onClick={() => remove(anchor.interactionAnchorId)}>删除</button></li>)}</ol>}</section>;
}
