"""Shared helpers for iFrame application-version management.

The repository keeps a plain-text ``VERSION`` as the canonical release value.
This module deliberately knows only about application-version surfaces; model
catalog and persisted-data schema versions are separate contracts.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
VERSION_PATH = ROOT / "VERSION"
SEMVER_RE = re.compile(
    r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)"
    r"(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)

JSON_VERSION_FILES = (
    Path("package.json"),
    Path("frontend/package.json"),
    Path("src-tauri/tauri.conf.json"),
)
README_FILES = (
    Path("README.md"),
    Path("README_EN.md"),
    Path("README_IFRAME.md"),
)


def validate_version(value: str) -> str:
    """Validate and return a normalized SemVer value."""
    normalized = value.strip()
    if not SEMVER_RE.fullmatch(normalized):
        raise ValueError(f"Invalid application version: {value!r}; expected MAJOR.MINOR.PATCH SemVer")
    return normalized


def read_version(path: Path = VERSION_PATH) -> str:
    """Read the canonical version and reject extra non-whitespace lines."""
    raw = path.read_text(encoding="utf-8")
    lines = raw.splitlines()
    if len(lines) != 1 or not lines[0].strip():
        raise ValueError(f"{path} must contain exactly one non-empty version line")
    return validate_version(lines[0])


def version_label(version: str) -> str:
    return f"V{validate_version(version)}"


def _root_path(root: Path, relative: Path) -> Path:
    return root / relative


def _replace_once(path: Path, pattern: str, replacement: str, *, flags: int = 0) -> None:
    text = path.read_text(encoding="utf-8")
    updated, count = re.subn(pattern, replacement, text, count=1, flags=flags)
    if count != 1:
        raise ValueError(f"Could not update exactly one version field in {path}")
    path.write_text(updated, encoding="utf-8")


def update_surfaces(version: str, *, root: Path = ROOT) -> None:
    """Write the canonical version to every application-version surface."""
    version = validate_version(version)
    version_file = _root_path(root, Path("VERSION"))
    version_file.write_text(f"{version}\n", encoding="utf-8")

    for relative in JSON_VERSION_FILES:
        path = _root_path(root, relative)
        # The first top-level version field is the package/application version;
        # nested dependency versions are intentionally outside this contract.
        _replace_once(path, r'("version"\s*:\s*")[^"]*(")', rf"\g<1>{version}\g<2>")
        json.loads(path.read_text(encoding="utf-8"))

    _replace_once(
        _root_path(root, Path("src-tauri/Cargo.toml")),
        r'(?m)^(version\s*=\s*")[^"]*(")',
        rf"\g<1>{version}\g<2>",
    )
    _replace_once(
        _root_path(root, Path("src-tauri/Cargo.lock")),
        r'(?ms)(\[\[package\]\]\nname = "iframe-studio"\nversion = ")[^"]*(")',
        rf"\g<1>{version}\g<2>",
    )
    _replace_once(
        _root_path(root, Path("src/apps/comic_gen/api.py")),
        r'(FastAPI\(title="iFrame Studio API", version=")[^"]*(")',
        rf"\g<1>{version}\g<2>",
    )

    generated = _root_path(root, Path("frontend/src/generated/appVersion.ts"))
    generated.parent.mkdir(parents=True, exist_ok=True)
    generated.write_text(
        "/* Generated by scripts/update_version.py; do not edit manually. */\n"
        f'export const APP_VERSION = "{version}" as const;\n'
        "export const APP_VERSION_LABEL = `V${APP_VERSION}` as const;\n",
        encoding="utf-8",
    )

    label = version_label(version)
    for relative in README_FILES:
        path = _root_path(root, relative)
        text = path.read_text(encoding="utf-8")
        updated, count = re.subn(
            r"(#{1,2}[^\n]*iFrame Studio )V[0-9A-Za-z.+-]+",
            rf"\g<1>{label}",
            text,
        )
        if count < 1:
            raise ValueError(f"No iFrame Studio release heading found in {path}")
        path.write_text(updated, encoding="utf-8")


def _read_json_version(path: Path) -> str:
    value = json.loads(path.read_text(encoding="utf-8")).get("version")
    return str(value)


def collect_mismatches(*, root: Path = ROOT, version: str | None = None) -> list[str]:
    """Return human-readable mismatches without modifying the tree."""
    expected = validate_version(version) if version is not None else read_version(_root_path(root, Path("VERSION")))
    label = version_label(expected)
    mismatches: list[str] = []

    for relative in JSON_VERSION_FILES:
        path = _root_path(root, relative)
        try:
            actual = _read_json_version(path)
        except (OSError, ValueError, TypeError, json.JSONDecodeError) as exc:
            mismatches.append(f"{relative}: unreadable version ({exc})")
            continue
        if actual != expected:
            mismatches.append(f"{relative}: {actual!r} != {expected!r}")

    checks: Iterable[tuple[Path, str, str]] = (
        (_root_path(root, Path("src-tauri/Cargo.toml")), r'(?m)^version\s*=\s*"([^"]+)"', "Cargo.toml"),
        (_root_path(root, Path("src-tauri/Cargo.lock")), r'(?ms)\[\[package\]\]\nname = "iframe-studio"\nversion = "([^"]+)"', "Cargo.lock"),
        (_root_path(root, Path("src/apps/comic_gen/api.py")), r'FastAPI\(title="iFrame Studio API", version="([^"]+)"', "FastAPI"),
    )
    for path, pattern, name in checks:
        text = path.read_text(encoding="utf-8") if path.exists() else ""
        match = re.search(pattern, text)
        actual = match.group(1) if match else None
        if actual != expected:
            mismatches.append(f"{name}: {actual!r} != {expected!r}")

    generated = _root_path(root, Path("frontend/src/generated/appVersion.ts"))
    generated_text = generated.read_text(encoding="utf-8") if generated.exists() else ""
    if f'APP_VERSION = "{expected}"' not in generated_text:
        mismatches.append(f"frontend/src/generated/appVersion.ts: missing {expected!r}")
    if f"APP_VERSION_LABEL = `V${{APP_VERSION}}`" not in generated_text:
        mismatches.append("frontend/src/generated/appVersion.ts: missing APP_VERSION_LABEL")

    for relative in (
        Path("frontend/src/components/settings/SettingsPage.tsx"),
        Path("frontend/src/components/layout/GlobalSidebar.tsx"),
    ):
        text = _root_path(root, relative).read_text(encoding="utf-8")
        if "@/generated/appVersion" not in text:
            mismatches.append(f"{relative}: does not import generated app version")

    pipeline = _root_path(root, Path("frontend/src/components/layout/PipelineSidebar.tsx"))
    if "@/generated/appVersion" not in pipeline.read_text(encoding="utf-8"):
        mismatches.append(f"{pipeline.relative_to(root)}: does not import generated app version")

    for relative in README_FILES:
        text = _root_path(root, relative).read_text(encoding="utf-8")
        headings = re.findall(r"#{1,2}[^\n]*iFrame Studio (V[0-9A-Za-z.+-]+)", text)
        if not headings or any(item != label for item in headings):
            mismatches.append(f"{relative}: release headings do not all use {label}")

    return mismatches
