export type CharacterImagePromptType = "full_body" | "three_view" | "headshot";
export type CharacterMotionPromptType = "full_body" | "headshot";

/**
 * Defaults generated by the workbench are intentionally Chinese. Creative
 * input supplied by the user (including an English style prompt) is kept as-is
 * by the caller and is not passed through this helper.
 */
export const DEFAULT_CHARACTER_NEGATIVE_PROMPT =
    "低质量，解剖结构错误，手部错误，文字，瑕疵，缺失手指，多余手指，裁切，最差质量，JPEG压缩伪影，签名，水印，模糊";

function cleanFragment(value: unknown): string {
    return String(value ?? "")
        .trim()
        .replace(/[。！？.!?]+$/, "");
}

function sentence(...fragments: unknown[]): string {
    const parts = fragments.map(cleanFragment).filter(Boolean);
    return parts.length ? `${parts.join("。")}。` : "";
}

export function buildCharacterImagePrompt(
    type: CharacterImagePromptType,
    name: string,
    description: string,
    preserveReference = false,
): string {
    const characterName = cleanFragment(name) || "角色";
    const characterDescription = cleanFragment(description);

    if (type === "full_body") {
        return sentence(
            preserveReference && "严格保持参考图中的角色外观、脸型、发型、肤色和服装",
            `全身角色设计：${characterName}`,
            "概念设计",
            characterDescription,
            "站立姿势，中性表情，正面看向镜头",
            "纯白背景，主体独立，无其他物体和场景，背景简洁，高质量，杰作级细节",
        );
    }

    if (type === "three_view") {
        return sentence(
            preserveReference && "严格保持参考图中的角色外观、脸型、发型和服装",
            `角色设定参考图：${characterName}`,
            characterDescription,
            "三视图角色设计：正面、侧面和背面",
            "全身站立，中性表情，所有视图保持服装与细节一致",
            "简洁白色背景，线条清晰，摄影棚光线，高质量",
        );
    }

    return sentence(
        preserveReference && "严格保持参考图中的角色面孔、发型、肤色和五官",
        `角色${characterName}的近景肖像`,
        characterDescription,
        "聚焦面部和肩部，刻画清晰的面部细节，中性表情，正面看向镜头",
        "高质量，杰作级细节",
    );
}

export function buildCharacterMotionPrompt(
    type: CharacterMotionPromptType,
    description: string,
    hasAudio: boolean,
): string {
    const characterDescription = cleanFragment(description);

    if (type === "full_body") {
        return [
            "全身角色参考视频。",
            sentence(characterDescription),
            hasAudio
                ? "站立姿势，轻微转移重心，自然手势，身体向左、向右各转动约30度。角色根据音频自然说话，口型与音频同步，面部表情自然。"
                : "站立姿势，轻微转移重心，说话时配合自然手势，身体向左、向右各转动约30度。角色自然说话，从一数到五。",
            "从头到脚取景，镜头稳定，平光。",
        ].join("\n");
    }

    return [
        "高保真肖像参考视频。",
        sentence(characterDescription),
        hasAudio
            ? "面向镜头，根据音频自然说话，口型与音频同步，面部表情自然，配合轻微头部动作和眨眼，呈现丰富的细微表情。"
            : "面向镜头自然说话，从一数到五，配合轻微头部动作、眨眼和丰富的细微表情。",
        "4K画质，摄影棚光线，镜头稳定。",
    ].join("\n");
}

export function buildCharacterVideoPrompt(name: string, description: string): string {
    return sentence(
        `电影感镜头：${cleanFragment(name) || "角色"}`,
        cleanFragment(description),
        "环顾四周，自然呼吸，轻微动作，高质量，4K画质",
    );
}

/** Existing generated prompts may use the old English scaffold. */
export function hasCharacterReferenceConstraint(prompt: string): boolean {
    return /严格保持参考图|STRICTLY MAINTAIN/i.test(prompt || "");
}
